### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by R3uan3** [yanis60/QtGradientEditor#1]
I'm trying to compile with qt 6.0 but i keep getting this compile error:
`\moc_qtgradienteditor.cpp(415,30): error C2027: use of undefined type 'QtGradientEditorPrivate'`

it doesnt work with recent versions?

**Comment by yanis60** [comment]
Not tested on recent version

**Comment by yanis60** [comment]
You don't need to compile it, just copy it to your project

**Comment by R3uan3** [comment]
Hi, thank you for the quick answer.
I meant i added all files to my project but it doesn't compile, getting the mentioned error. 
What version did you use?

**Comment by yanis60** [comment]
Extracted from qt 5.15

**Comment by R3uan3** [comment]
I see, i will try to extract the same exact files from the 6.~ source and see if I can get it to compile.

**Comment by R3uan3** [comment]
I didn't succeed in getting it working with recent files, i had never touched the sources before, its so confuse :(

**Comment by R3uan3** [comment]
When the QGradientDialog is opened with `gradientDialog->open()` how to know when the "ok" button is clicked?
Im not launching it as:
```c++
    bool ok;
    QGradient gradient = QtGradientDialog::getGradient(&ok, QLinearGradient(), this);
    if (!ok)
```
to dont lock the QMainWindow

I tried
```c++
        QObject::connect(gradientDialog, &QtGradientDialog::accept, [this] {});
```
but: `QObject::connect: signal not found in QtGradientDialog`

**Comment by yanis60** [comment]
You need to cast it before

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
